# Generated by Django 5.0.6 on 2024-10-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgName', models.TextField()),
                ('createdBy', models.CharField(max_length=250)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
